#!/usr/bin/env bash
# Provision SSH hostname on existing cursor-web-bridge tunnel + deploy to 125.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLOUDFLARED="${CLOUDFLARED:-$ROOT/bin/cloudflared}"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-cursor-web-bridge}"
HTTP_HOSTNAME="${CLOUDFLARE_HOSTNAME:-cursor.david-x.com}"
SSH_HOSTNAME="${CLOUDFLARE_SSH_HOSTNAME:-ssh-125.david-x.com}"
TUNNEL_ID="${CLOUDFLARE_TUNNEL_ID:-3c6d63d3-9b8b-4b2b-bd3f-0189a20945e6}"
REMOTE_HOST="${REMOTE_HOST:-cursor-125}"
REMOTE_ROOT="${REMOTE_ROOT:-/home/yao/Projects/cursor-web-bridge}"
REMOTE_CRED="/home/yao/.cloudflared/${TUNNEL_ID}.json"

ACCESS_EMAILS=(
  "xudazhong@autel.com"
  "13238077823@163.com"
)

if [[ ! -x "$CLOUDFLARED" ]]; then
  echo "缺少 cloudflared: $CLOUDFLARED"
  exit 1
fi

cat > "$ROOT/config/cloudflared.yml" <<EOF
# Cloudflare Named Tunnel — runs on 10.229.20.125
# Generated by scripts/setup-ssh-125-access.sh

tunnel: ${TUNNEL_ID}
credentials-file: ${REMOTE_CRED}

ingress:
  - hostname: ${HTTP_HOSTNAME}
    service: http://127.0.0.1:8787
  - hostname: ${SSH_HOSTNAME}
    service: ssh://127.0.0.1:22
  - service: http_status:404
EOF

echo "==> DNS: ${SSH_HOSTNAME} -> tunnel ${TUNNEL_NAME}"
"$CLOUDFLARED" tunnel route dns -f "$TUNNEL_NAME" "$SSH_HOSTNAME"

echo "==> 同步配置到 ${REMOTE_HOST}:${REMOTE_ROOT}/config/cloudflared.yml"
if scp -o BatchMode=yes -o ConnectTimeout=12 "$ROOT/config/cloudflared.yml" \
  "${REMOTE_HOST}:${REMOTE_ROOT}/config/cloudflared.yml"; then
  echo "==> 重启 125 上的 named tunnel（保留 uvicorn）"
  ssh -o BatchMode=yes -o ConnectTimeout=12 "$REMOTE_HOST" bash -s <<EOF
set -euo pipefail
ROOT="${REMOTE_ROOT}"
CLOUDFLARED="\$ROOT/bin/cloudflared"
mkdir -p "\$ROOT/logs"
pkill -f "cloudflared tunnel --config" 2>/dev/null || true
pkill -f "cloudflared tunnel run" 2>/dev/null || true
sleep 1
nohup "\$CLOUDFLARED" tunnel --config "\$ROOT/config/cloudflared.yml" run \
  >> "\$ROOT/logs/tunnel.log" 2>&1 &
echo "cloudflared pid=\$!"
sleep 2
pgrep -af "cloudflared tunnel" | head -5
grep -E 'hostname:|service:' "\$ROOT/config/cloudflared.yml"
EOF
else
  echo "WARN: LAN scp/ssh 到 ${REMOTE_HOST} 失败（可能不在公司网）" >&2
  if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    echo "==> 尝试 Cloudflare API 远程推送 ingress..."
    INCLUDE_SSH=1 "$ROOT/scripts/push-tunnel-config-api.sh"
  else
    echo "    可选 1: 连公司 VPN 后重跑本脚本" >&2
    echo "    可选 2: 设置 CLOUDFLARE_API_TOKEN 后运行 scripts/push-tunnel-config-api.sh" >&2
    exit 1
  fi
fi

echo ""
echo "=========================================="
echo "  隧道侧已完成"
echo "=========================================="
echo "HTTP: https://${HTTP_HOSTNAME}"
echo "SSH:  ${SSH_HOSTNAME}"
echo ""
echo "接下来在 Cloudflare Zero Trust 创建 Access 应用："
echo "  1. https://one.dash.cloudflare.com/ -> Access controls -> Applications"
echo "  2. Add -> Self-hosted"
echo "  3. Application domain: ${SSH_HOSTNAME}"
echo "  4. Session duration: 24 hours"
echo "  5. Policy Allow, include emails:"
for email in "${ACCESS_EMAILS[@]}"; do
  echo "       - ${email}"
done
echo ""
echo "本机 SSH 片段（已可手动写入 ~/.ssh/config）："
cat <<SSHCFG

Host cursor-125-public
  HostName ${SSH_HOSTNAME}
  User yao
  IdentityFile ~/.ssh/cursor_webbridge_125
  IdentitiesOnly yes
  ProxyCommand ${CLOUDFLARED} access ssh --hostname %h
SSHCFG
