#!/usr/bin/env bash
# Expose a26125@10.229.20.110 SSH via existing cursor-web-bridge tunnel on 125.
# Public hostname: ssh-110.david-x.com → ssh://10.229.20.110:22 (from 125 LAN).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

CLOUDFLARED="${CLOUDFLARED:-$ROOT/bin/cloudflared}"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-cursor-web-bridge}"
TUNNEL_ID="${CLOUDFLARE_TUNNEL_ID:-3c6d63d3-9b8b-4b2b-bd3f-0189a20945e6}"
HTTP_HOSTNAME="${CLOUDFLARE_HOSTNAME:-cursor.david-x.com}"
SSH125_HOSTNAME="${CLOUDFLARE_SSH_HOSTNAME:-ssh-125.david-x.com}"
SSH110_HOSTNAME="${CLOUDFLARE_SSH110_HOSTNAME:-ssh-110.david-x.com}"
SSH110_TARGET="${CLOUDFLARE_SSH110_TARGET:-ssh://10.229.20.110:22}"
REMOTE_HOST="${REMOTE_HOST:-cursor-125-public}"
REMOTE_ROOT="${REMOTE_ROOT:-/home/yao/Projects/cursor-web-bridge}"
REMOTE_CRED="/home/yao/.cloudflared/${TUNNEL_ID}.json"

ACCESS_EMAILS=(
  "xudazhong@autel.com"
  "13238077823@163.com"
)

if [[ ! -x "$CLOUDFLARED" ]]; then
  echo "缺少 cloudflared: $CLOUDFLARED" >&2
  exit 1
fi

cat > "$ROOT/config/cloudflared.yml" <<EOF
# Cloudflare Named Tunnel — runs on 10.229.20.125
# Generated by scripts/setup-ssh-110-access.sh

tunnel: ${TUNNEL_ID}
credentials-file: ${REMOTE_CRED}

ingress:
  - hostname: ${HTTP_HOSTNAME}
    service: http://127.0.0.1:8787
  - hostname: ${SSH125_HOSTNAME}
    service: ssh://127.0.0.1:22
  - hostname: ${SSH110_HOSTNAME}
    service: ${SSH110_TARGET}
  - service: http_status:404
EOF

echo "==> DNS: ${SSH110_HOSTNAME} -> tunnel ${TUNNEL_NAME}"
"$CLOUDFLARED" tunnel route dns -f "$TUNNEL_NAME" "$SSH110_HOSTNAME"

echo "==> 同步配置到 ${REMOTE_HOST}:${REMOTE_ROOT}/config/cloudflared.yml"
if scp -o BatchMode=yes -o ConnectTimeout=25 "$ROOT/config/cloudflared.yml" \
  "${REMOTE_HOST}:${REMOTE_ROOT}/config/cloudflared.yml"; then
  echo "==> 重启 125 上的 named tunnel（保留 uvicorn）"
  ssh -o BatchMode=yes -o ConnectTimeout=25 "$REMOTE_HOST" bash -s <<EOF
set -euo pipefail
ROOT="${REMOTE_ROOT}"
CLOUDFLARED="\$ROOT/bin/cloudflared"
mkdir -p "\$ROOT/logs"
pkill -f "cloudflared tunnel --config" 2>/dev/null || true
pkill -f "cloudflared tunnel run" 2>/dev/null || true
sleep 1
nohup "\$CLOUDFLARED" tunnel --config "\$ROOT/config/cloudflared.yml" run \
  >> "\$ROOT/logs/tunnel.log" 2>&1 &
echo "cloudflared pid=\$!"
sleep 2
pgrep -af "cloudflared tunnel" | head -5
grep -E 'hostname:|service:' "\$ROOT/config/cloudflared.yml"
# confirm 110:22 reachable from 125
nc -zv -w 3 10.229.20.110 22 || true
EOF
else
  echo "WARN: scp/ssh 到 ${REMOTE_HOST} 失败" >&2
  if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    echo "==> Cloudflare API 推送 ingress（含 ssh-110）..."
    INCLUDE_SSH=1 INCLUDE_SSH110=1 "$ROOT/scripts/push-tunnel-config-api.sh"
  else
    exit 1
  fi
fi

# Also push remote config so cloudflare-managed mode stays in sync
if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  INCLUDE_SSH=1 INCLUDE_SSH110=1 "$ROOT/scripts/push-tunnel-config-api.sh" || true
fi

echo ""
echo "=========================================="
echo "  110 公网 SSH 隧道侧已完成"
echo "=========================================="
echo "HTTP:     https://${HTTP_HOSTNAME}"
echo "SSH-125:  ${SSH125_HOSTNAME}"
echo "SSH-110:  ${SSH110_HOSTNAME} -> ${SSH110_TARGET}"
echo ""
echo "Access 应用（若尚未创建）："
echo "  Domain: ${SSH110_HOSTNAME}"
echo "  Session: 24 hours"
echo "  Allow emails:"
for email in "${ACCESS_EMAILS[@]}"; do
  echo "    - ${email}"
done
echo ""
echo "本机 SSH："
echo "  ssh a26125-110-public"
